In [1]:
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import pandas as pd

In [3]:
import datetime as dt

# Reflect Tables into SQLAlchemy ORM

In [4]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, func, desc

In [5]:
engine = create_engine("sqlite:///Resources/hawaii.sqlite")

In [6]:
# reflect an existing database into a new model
Base = automap_base()

# reflect the tables
Base.prepare(engine, reflect=True)

In [7]:
# We can view all of the classes that automap found
Base.classes.keys()

['measurement', 'station']

In [8]:
# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [9]:
# Create our session (link) from Python to the DB
session = Session(engine)

# Exploratory Climate Analysis

In [10]:
# Design a query to retrieve the last 12 months of precipitation data and plot the results
#
#

In [11]:
inspector = inspect(engine)
inspector.get_table_names()

['measurement', 'station']

In [12]:
#determining columns from each table
m_columns = inspector.get_columns('measurement')
print("Measurement columns:")
for m in m_columns:
    print(m['name'],m['type'])
print()
s_columns = inspector.get_columns('station')
print("Station columns:")
for s in s_columns:
    print(s['name'],s['type'])

Measurement columns:
id INTEGER
station TEXT
date TEXT
prcp FLOAT
tobs FLOAT

Station columns:
id INTEGER
station TEXT
name TEXT
latitude FLOAT
longitude FLOAT
elevation FLOAT

In [13]:
# Calculate the date 1 year ago from the last data point in the database

latest_date = session.query(Measurement).order_by(desc('date')).first()
print(latest_date.date)

2017-08-23

In [14]:
#joining tables
# Perform a query to retrieve the data and precipitation scores

sel = Measurement.id,Measurement.station,Station.name,Station.latitude,Station.longitude,Station.elevation,Measurement.date,Measurement.prcp
merged_tb = session.query(*sel).filter(Measurement.station == Station.station)\
                                .filter(Measurement.date > '2016-08-23').all()

In [16]:
# query results as a Pandas DataFrame and set the index to the date column
# Sort the dataframe by date

df = pd.DataFrame(merged_tb,columns=['Index','Station','Station_Name','Latitiude','Longitude','Elevation','Date','Precipitation'])
df = df.drop(columns=['Index'])
df.sort_values(by=['Date'],inplace=True,ascending=False)
df.set_index('Date',inplace=True)

df.head(50)

,Station,Station_Name,Latitiude,Longitude,Elevation,Precipitation
Date,,,,,,
2017-08-23,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.45
2017-08-23,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.08
2017-08-23,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.00
2017-08-23,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-22,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.00
2017-08-22,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.50
2017-08-22,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-21,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.56
2017-08-21,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.02
2017-08-21,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,NaN
2017-08-21,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-20,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.01
2017-08-20,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,NaN
2017-08-20,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-19,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.09
2017-08-19,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,NaN
2017-08-19,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-19,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.00
2017-08-18,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.00
2017-08-18,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9,0.06
2017-08-18,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-18,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,NaN
2017-08-17,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.05
2017-08-17,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.00
2017-08-17,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9,0.01
2017-08-17,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.13
2017-08-16,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.42
2017-08-16,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.07
2017-08-16,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.00
2017-08-16,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9,0.12
2017-08-15,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.00
2017-08-15,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.42
2017-08-15,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.02
2017-08-15,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9,0.32
2017-08-15,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.06
2017-08-14,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9,0.00
2017-08-14,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.22
2017-08-14,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.08
2017-08-14,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-14,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,0.01
2017-08-13,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9,0.00
2017-08-13,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-13,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,NaN
2017-08-13,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0,NaN
2017-08-13,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.00
2017-08-12,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4,0.14
2017-08-12,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.00
2017-08-12,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-11,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0,0.00
2017-08-11,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5,0.00

In [ ]:
# Use Pandas Plotting with Matplotlib to plot the data

In [ ]:
# Use Pandas to calculate the summary statistics for the precipitation data

In [ ]:
# Design a query to show how many stations are available in this dataset?

In [ ]:
# What are the most active stations? (i.e. what stations have the most rows)?
# List the stations and the counts in descending order.

In [ ]:
# Using the station id from the previous query, calculate the lowest temperature recorded, 
# highest temperature recorded, and average temperature of the most active station?

In [ ]:
# Choose the station with the highest number of temperature observations.
# Query the last 12 months of temperature observation data for this station and plot the results as a histogram

## Bonus Challenge Assignment

In [ ]:
# This function called `calc_temps` will accept start date and end date in the format '%Y-%m-%d' 
# and return the minimum, average, and maximum temperatures for that range of dates
def calc_temps(start_date, end_date):
    """TMIN, TAVG, and TMAX for a list of dates.
    
    Args:
        start_date (string): A date string in the format %Y-%m-%d
        end_date (string): A date string in the format %Y-%m-%d
        
    Returns:
        TMIN, TAVE, and TMAX
    """
    
    return session.query(func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)).\
        filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).all()

# function usage example
print(calc_temps('2012-02-28', '2012-03-05'))

In [ ]:
# Use your previous function `calc_temps` to calculate the tmin, tavg, and tmax 
# for your trip using the previous year's data for those same dates.

In [ ]:
# Plot the results from your previous query as a bar chart. 
# Use "Trip Avg Temp" as your Title
# Use the average temperature for the y value
# Use the peak-to-peak (tmax-tmin) value as the y error bar (yerr)

In [ ]:
# Calculate the total amount of rainfall per weather station for your trip dates using the previous year's matching dates.
# Sort this in descending order by precipitation amount and list the station, name, latitude, longitude, and elevation

In [ ]:
# Create a query that will calculate the daily normals 
# (i.e. the averages for tmin, tmax, and tavg for all historic data matching a specific month and day)

def daily_normals(date):
    """Daily Normals.
    
    Args:
        date (str): A date string in the format '%m-%d'
        
    Returns:
        A list of tuples containing the daily normals, tmin, tavg, and tmax
    
    """
    
    sel = [func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)]
    return session.query(*sel).filter(func.strftime("%m-%d", Measurement.date) == date).all()
    
daily_normals("01-01")

In [ ]:
# calculate the daily normals for your trip
# push each tuple of calculations into a list called `normals`

# Set the start and end date of the trip

# Use the start and end date to create a range of dates

# Stip off the year and save a list of %m-%d strings

# Loop through the list of %m-%d strings and calculate the normals for each date

In [ ]:
# Load the previous query results into a Pandas DataFrame and add the `trip_dates` range as the `date` index

In [ ]:
# Plot the daily normals as an area plot with `stacked=False`